### ISSUE TITLE
which pc soft use

### ISSUE THREAD

**Issue by JustQY** [ryedwards/budgetcan_fw#7]

**Comment by fred314159265** [comment]
@JustQY Since this firmware implements the gs_usb protocol, you can use it natively with Linux using [SocketCAN](https://www.kernel.org/doc/html/v5.11/networking/can.html), or if you are not on Linux you should be able to get somewhere using python-can as it [supports gs_usb](https://python-can.readthedocs.io/en/stable/interfaces/gs_usb.html) on all platforms.
